services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    stop_signal: SIGINT
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/video0:/dev/video0"
      - "/dev/video2:/dev/video2"
    volumes:
      - /dev:/dev
    #network_mode: "host"
    environment:
      - CAMERA_INDEX=0
      - SERIAL_PORT=/dev/ttyUSB0
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
